config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'
  resources :bloco_aptos
  resources :telefones
  resources :carros
  resources :moradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carro.rb
class Carro < ApplicationRecord
  belongs_to :morador
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy]

  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1
  # GET /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1
  # PATCH/PUT /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: 'Carro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carro_params
      params.require(:carro).permit(:placa, :modelo, :cor, :morador_id)
    end
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_form.html.erb
<%= form_with(model: carro, local: true) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :placa %>
    <%= form.text_field :placa %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="field">
    <%= form.label :morador_id %>
    <%= form.text_field :morador_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Modelo</th>
      <th>Cor</th>
      <th>Morador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.placa %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.cor %></td>
        <td><%= carro.morador %></td>
        <td><%= link_to 'Show', carro %></td>
        <td><%= link_to 'Edit', edit_carro_path(carro) %></td>
        <td><%= link_to 'Destroy', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carro', new_carro_path %>

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @carro.placa %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @carro.modelo %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @carro.cor %>
</p>

<p>
  <strong>Morador:</strong>
  <%= @carro.morador %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>