config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'
  resources :bloco_aptos
  resources :telefones
  resources :carros
  resources :moradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bloco_apto.rb
class BlocoApto < ApplicationRecord
  belongs_to :morador, optional:true
end

app/controllers/bloco_aptos_controller.rb
class BlocoAptosController < ApplicationController
  before_action :set_bloco_apto, only: [:show, :edit, :update, :destroy]

  # GET /bloco_aptos
  # GET /bloco_aptos.json
  def index
    @bloco_aptos = BlocoApto.all.order(:bloco_apto_int)
  end

  # GET /bloco_aptos/1
  # GET /bloco_aptos/1.json
  def show
  end

  # GET /bloco_aptos/new
  def new
    @bloco_apto = BlocoApto.new
  end

  # GET /bloco_aptos/1/edit
  def edit
  end

  # POST /bloco_aptos
  # POST /bloco_aptos.json
  def create
    @bloco_apto = BlocoApto.new(bloco_apto_params)

    respond_to do |format|
      if @bloco_apto.save
        format.html { redirect_to @bloco_apto, notice: 'Bloco apto was successfully created.' }
        format.json { render :show, status: :created, location: @bloco_apto }
      else
        format.html { render :new }
        format.json { render json: @bloco_apto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloco_aptos/1
  # PATCH/PUT /bloco_aptos/1.json
  def update
    respond_to do |format|
      if @bloco_apto.update(bloco_apto_params)
        format.html { redirect_to @bloco_apto, notice: 'Bloco apto was successfully updated.' }
        format.json { render :show, status: :ok, location: @bloco_apto }
      else
        format.html { render :edit }
        format.json { render json: @bloco_apto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloco_aptos/1
  # DELETE /bloco_aptos/1.json
  def destroy
    @bloco_apto.destroy
    respond_to do |format|
      format.html { redirect_to bloco_aptos_url, notice: 'Bloco apto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bloco_apto
      @bloco_apto = BlocoApto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bloco_apto_params
      params.require(:bloco_apto).permit(:bloco, :apto, :morador_id)
    end
end

app/helpers/bloco_aptos_helper.rb
module BlocoAptosHelper
end

app/views/bloco_aptos/_form.html.erb
<%= form_with(model: bloco_apto, local: true) do |form| %>
  <% if bloco_apto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bloco_apto.errors.count, "error") %> prohibited this bloco_apto from being saved:</h2>

      <ul>
      <% bloco_apto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bloco %>
    <%= form.text_field :bloco %>
  </div>

  <div class="field">
    <%= form.label :apto %>
    <%= form.text_field :apto %>
  </div>

  <div class="field">
    <%= form.label :morador_id %>
    <%= form.text_field :morador_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bloco_aptos/edit.html.erb
<h1>Editing Bloco Apto</h1>

<%= render 'form', bloco_apto: @bloco_apto %>

<%= link_to 'Show', @bloco_apto %> |
<%= link_to 'Back', bloco_aptos_path %>

app/views/bloco_aptos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloco Aptos</h1>
<%= link_to 'New Bloco Apto', new_bloco_apto_path %>
<br>
<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>Bloco</th>
      <th>Apto</th>
      <th>Morador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloco_aptos.each do |bloco_apto| %>
      <tr>
        <td><%= bloco_apto.bloco %></td>
        <td><%= bloco_apto.apto %></td>
        <td><%= bloco_apto.morador.nome %></td>
        <td><%= link_to 'Show', bloco_apto %></td>
        <td><%= link_to 'Edit', edit_bloco_apto_path(bloco_apto) %></td>
        <td><%= link_to 'Destroy', bloco_apto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>Bloco</th>
      <th>Apto</th>
      <th>Morador</th>
      <th colspan="3"></th>
    </tr>
  </tfoot>
</table>

app/views/bloco_aptos/new.html.erb
<h1>New Bloco Apto</h1>

<%= render 'form', bloco_apto: @bloco_apto %>

<%= link_to 'Back', bloco_aptos_path %>

app/views/bloco_aptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bloco:</strong>
  <%= @bloco_apto.bloco %>
</p>

<p>
  <strong>Apto:</strong>
  <%= @bloco_apto.apto %>
</p>

<p>
  <strong>Morador:</strong>
  <%= @bloco_apto.morador %>
</p>

<%= link_to 'Edit', edit_bloco_apto_path(@bloco_apto) %> |
<%= link_to 'Back', bloco_aptos_path %>