config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'
  resources :bloco_aptos
  resources :telefones
  resources :carros
  resources :moradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/telefone.rb
class Telefone < ApplicationRecord
  belongs_to :morador
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  before_action :set_telefone, only: [:show, :edit, :update, :destroy]

  # GET /telefones
  # GET /telefones.json
  def index
    @telefones = Telefone.all
  end

  # GET /telefones/1
  # GET /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefone.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones
  # POST /telefones.json
  def create
    @telefone = Telefone.new(telefone_params)

    respond_to do |format|
      if @telefone.save
        format.html { redirect_to @telefone, notice: 'Telefone was successfully created.' }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1
  # PATCH/PUT /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to @telefone, notice: 'Telefone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1
  # DELETE /telefones/1.json
  def destroy
    @telefone.destroy
    respond_to do |format|
      format.html { redirect_to telefones_url, notice: 'Telefone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefone
      @telefone = Telefone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telefone_params
      params.require(:telefone).permit(:num_telefone, :morador_id)
    end
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/views/telefones/_form.html.erb
<%= form_with(model: telefone, local: true) do |form| %>
  <% if telefone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
      <% telefone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :num_telefone %>
    <%= form.text_field :num_telefone %>
  </div>

  <div class="field">
    <%= form.label :morador_id %>
    <%= form.text_field :morador_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/edit.html.erb
<h1>Editing Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Show', @telefone %> |
<%= link_to 'Back', telefones_path %>

app/views/telefones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telefones</h1>

<table>
  <thead>
    <tr>
      <th>Num telefone</th>
      <th>Morador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefones.each do |telefone| %>
      <tr>
        <td><%= telefone.num_telefone %></td>
        <td><%= telefone.morador %></td>
        <td><%= link_to 'Show', telefone %></td>
        <td><%= link_to 'Edit', edit_telefone_path(telefone) %></td>
        <td><%= link_to 'Destroy', telefone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefone', new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Back', telefones_path %>

app/views/telefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num telefone:</strong>
  <%= @telefone.num_telefone %>
</p>

<p>
  <strong>Morador:</strong>
  <%= @telefone.morador %>
</p>

<%= link_to 'Edit', edit_telefone_path(@telefone) %> |
<%= link_to 'Back', telefones_path %>