config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'
  resources :bloco_aptos
  resources :telefones
  resources :carros
  resources :moradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/morador.rb
class Morador < ApplicationRecord
    has_many :carros, dependent: :destroy
    has_many :telefones, dependent: :destroy
    has_one :bloco_apto, dependent: :destroy

    accepts_nested_attributes_for :bloco_apto
    accepts_nested_attributes_for :carros, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :telefones, reject_if: :all_blank, allow_destroy: true
end

app/controllers/moradors_controller.rb
class MoradorsController < ApplicationController
  before_action :set_morador, only: [:show, :edit, :update, :destroy]

  # GET /moradors
  # GET /moradors.json
  def index
    @moradors = Morador.all.order(:bloco_apto_int)
  end

  # GET /moradors/1
  # GET /moradors/1.json
  def show
  end

  # GET /moradors/new
  def new
    @morador = Morador.new
    @morador.build_bloco_apto
    # Para has_many => @morador.bloco_apto.build
  end

  # GET /moradors/1/edit
  def edit
    
  end

  # POST /moradors
  # POST /moradors.json
  def create
    @morador = Morador.new(morador_params)
    @morador.bloco_apto_int = "#{@morador.bloco_apto.bloco}#{@morador.bloco_apto.apto}".to_i
    @morador.bloco_apto.bloco_apto_int = "#{@morador.bloco_apto.bloco}#{@morador.bloco_apto.apto}".to_i
    respond_to do |format|
      if @morador.save!
        
        format.html { redirect_to @morador, notice: 'Morador was successfully created.' }
        format.json { render :show, status: :created, location: @morador }
      else
        format.html { render :new }
        format.json { render json: @morador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moradors/1
  # PATCH/PUT /moradors/1.json
  def update
    @morador.bloco_apto_int = "#{@morador.bloco_apto.bloco}#{@morador.bloco_apto.apto}".to_i
    @morador.bloco_apto.bloco_apto_int = "#{@morador.bloco_apto.bloco}#{@morador.bloco_apto.apto}".to_i
    respond_to do |format|
      if @morador.update(morador_params)
        format.html { redirect_to @morador, notice: 'Morador was successfully updated.' }
        format.json { render :show, status: :ok, location: @morador }
      else
        format.html { render :edit }
        format.json { render json: @morador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moradors/1
  # DELETE /moradors/1.json
  def destroy
    @morador.destroy
    respond_to do |format|
      format.html { redirect_to moradors_url, notice: 'Morador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morador
      @morador = Morador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def morador_params
      params.require(:morador).permit(
        :nome, 
        :cpf, 
        :email, 
        :tipo,
        bloco_apto_attributes:[
          :bloco,
          :apto
        ],
        telefones_attributes:[
          :id,
          :num_telefone,
          :_destroy
        ],
        carros_attributes:[
          :id,
          :placa,
          :modelo,
          :cor,
          :_destroy
        ]
      )
    end
end

app/helpers/moradors_helper.rb
module MoradorsHelper
end

app/views/moradors/_carro_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :placa %>
        <%= f.text_field :placa, class: "carro-field" %>
        <%= f.label :modelo %>
        <%= f.text_field :modelo, class: "carro-field" %>
        <%= f.label :cor %>
        <%= f.text_field :cor, class: "carro-field" %>
        <%= link_to_remove_association("remover", f) %>
    </div>
</div>

app/views/moradors/_form.html.erb
<%= form_with(model: morador, class: "form", local: true) do |form| %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :tipo %>
    <%= form.select :tipo, options_for_tipos_func_application_helper(@morador.tipo) %>
  </div>

  <%= form.fields_for :bloco_apto do |bloco_apto_fields|%>
    <div class="form-group">
      <%= bloco_apto_fields.label :bloco %>
      <%= bloco_apto_fields.select :bloco, options_for_blocos_func_application_helper(@morador.bloco_apto.bloco) %>
    </div>
    <div class="form-group">
      <%= bloco_apto_fields.label :apto %>
      <%= bloco_apto_fields.select :apto, options_for_aptos_func_application_helper(@morador.bloco_apto.apto) %>
    </div>
  <% end %>

  <div id="telefones">
    <%= form.label :telefones %>

    <%= form.fields_for :telefones do |telefones_fields| %>
      <%= render partial: "telefone_fields", locals: {f: telefones_fields} %>
    <% end %>

    <div class="form-group">
      <%= form.label :telefones, ">" %><br>
      <%= link_to_add_association('[Adicionar Telefone]', form, :telefones) %>
    </div>

  </div>

  <div id="carros">
    <%= form.label :carros %>
    
    <%= form.fields_for :carros do |carros_fields| %>
      <%= render partial: "carro_fields", locals: {f: carros_fields} %>
    <% end %>

    <div class="form-group">
      <%= form.label :carros, ">" %><br>
      <%= link_to_add_association('[Adicionar Carro]', form, :carros) %>
    </div>

  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>

  <% if morador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(morador.errors.count, "error") %> prohibited this morador from being saved:</h2>

      <ul>
      <% morador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/moradors/_telefone_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.text_field :num_telefone, class: "form-control" %>
        <%= link_to_remove_association("remover", f) %>
    </div>
</div>

app/views/moradors/edit.html.erb
<h1>Editing Morador</h1>

<%= render 'form', morador: @morador %>

<%= link_to 'Show', @morador %> |
<%= link_to 'Back', moradors_path %>

app/views/moradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moradors</h1>
<%= link_to 'New Morador', new_morador_path %>
<br>
<br>
<table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>Bl | Ap</th>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Tipo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @moradors.each do |morador| %>
      <tr>
        <td><%= "#{morador.bloco_apto.bloco}#{morador.bloco_apto.apto}".to_i %></td>
        <td><%= morador.nome %></td>
        <td><%= morador.cpf %></td>
        <td><%= morador.email %></td>
        <td><%= morador.tipo %></td>
        <td>
          <%= link_to 'Show', morador %>
          <%= link_to 'Edit', edit_morador_path(morador) %>
          <%= link_to 'Destroy', morador, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>Bl | Ap</th>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Tipo</th>
      <th></th>
    </tr>
  </tfoot>
</table>
<%= link_to 'New Morador', new_morador_path %>

app/views/moradors/new.html.erb
<h1>New Morador</h1>

<%= render 'form', morador: @morador %>

<%= link_to 'Back', moradors_path %>

app/views/moradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @morador.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @morador.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @morador.email %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @morador.tipo %>
</p>

<%= link_to 'Edit', edit_morador_path(@morador) %> |
<%= link_to 'Back', moradors_path %>